Repository outline/outline, pull requests merged in 2021-08, with the labels that each got.

#2337 feat: Optimize Dockerfile
  Dockerfile
Labels: performance

#2397 perf: Remove backup column migration
  server/migrations/20210730044247-remove-backup-column.js
Labels: blocked, performance

#2400 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/zh_CN/translation.json
Labels: more information needed

#2395 perf: Remove unused database indexes according to production data
  server/migrations/20210730042450-remove-unused-indexes.js
Labels: performance

#2334 feat: Include more events in document history sidebar
  app/components/Button.js
  app/components/DocumentHistory.js
  app/components/DocumentHistory/DocumentHistory.js
  app/components/DocumentHistory/components/Revision.js
  app/components/DocumentHistory/index.js
  app/components/EventListItem.js
  app/components/List/Item.js
  app/components/LocaleTime.js
  app/components/NavLink.js
  app/components/NudeButton.js
  app/components/PaginatedEventList.js
  app/components/PaginatedList.js
  app/components/PaginatedList.test.js
  app/components/Tab.js
  app/components/Time.js
  app/menus/RevisionMenu.js
  app/models/Event.js
  app/stores/EventsStore.js
  app/stores/RootStore.js
  app/test/setup.js
  app/utils/dates.js
  shared/i18n/locales/en_US/translation.json
Labels: enhancement

#2413 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2450 fix: Improvements in table component
  app/components/Table.js
  app/scenes/Settings/People.js
  shared/i18n/locales/en_US/translation.json
Labels: more information needed
