Repository outline/outline, pull requests merged in 2021-07, with the labels that each got.

#2262 New Crowdin updates
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2267 New Crowdin updates
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2268 New Crowdin updates
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2271 New Crowdin updates
  shared/i18n/locales/pt_BR/translation.json
Labels: more information needed

#2281 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2310 feat: Improved UI motion design
  app/components/ContextMenu/index.js
  app/components/DocumentListItem.js
  app/components/HoverPreview.js
  app/components/PaginatedDocumentList.js
  app/components/Tab.js
  app/components/Tabs.js
  app/index.js
  app/utils/motion.js
  package.json
  shared/styles/animations.js
  yarn.lock
Labels: little details

#2293 feat: Add Google DataStudio embed
  app/embeds/GoogleDataStudio.js
  app/embeds/GoogleDataStudio.test.js
  app/embeds/index.js
  public/images/google-datastudio.png
Labels: more information needed

#2322 chore: Loading placeholders
  app/components/DocumentHistory/DocumentHistory.js
  app/components/Flex.js
  app/components/List/Placeholder.js
  app/components/LoadingPlaceholder/ListPlaceholder.js
  app/components/LoadingPlaceholder/index.js
  app/components/PaginatedList.js
  app/components/PlaceholderDocument.js
  app/components/PlaceholderText.js
  app/components/Sidebar/components/Collections.js
  app/components/Sidebar/components/CollectionsLoading.js
  app/components/Sidebar/components/PlaceholderCollections.js
  app/components/Table.js
  app/routes/authenticated.js
  app/scenes/Collection.js
  app/scenes/Document/components/Document.js
  app/scenes/Document/components/Loading.js
  app/scenes/DocumentNew.js
Labels: little details

#2314 feat: `useBoolean` hook
  app/components/DocumentListItem.js
  app/components/Sidebar/components/CollectionLink.js
  app/components/Sidebar/components/DocumentLink.js
  app/hooks/useBoolean.js
  app/menus/AccountMenu.js
  app/scenes/Collection.js
  app/scenes/CollectionPermissions/index.js
  app/scenes/Document/components/KeyboardShortcutsButton.js
  app/scenes/Settings/Groups.js
  app/scenes/Settings/People.js
  app/scenes/Settings/Tokens.js
Labels: techdebt

#2304 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2344 chore: Move animations and globals from shared directory
  app/components/Bubble.js
  app/components/ContextMenu/index.js
  app/components/Editor.js
  app/components/Fade.js
  app/components/HoverPreview.js
  app/components/Modal.js
  app/components/PlaceholderText.js
  app/components/Popover.js
  app/components/Sidebar/Sidebar.js
  app/components/Theme.js
  app/components/Toast.js
  app/scenes/Document/components/Editor.js
  app/stores/UiStore.js
  app/styles/animations.js
  app/styles/globals.js
  app/types/index.js
  server/emails/components/EmailLayout.js
  server/emails/components/Footer.js
  shared/theme.js
Labels: techdebt

#2341 feat: Enable Persian language translations
  app/components/LocaleTime.js
  shared/i18n/index.js
Labels: i18n

#2340 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: i18n, more information needed

#2351 chore: Improve perf of new tab loading
  app/stores/AuthStore.js
  app/stores/RootStore.js
Labels: performance

#2368 New Crowdin updates
  shared/i18n/locales/pt_BR/translation.json
Labels: more information needed

#2347 feat: Web concurrency
  .env.sample
  package.json
  server/index.js
  server/main.js
  server/sequelize.js
  yarn.lock
Labels: performance

#2342 fix: Show tasks completion on document list items
  app/components/CircularProgressBar.js
  app/components/DocumentMeta.js
  app/components/DocumentTasks.js
  app/models/Document.js
  app/scenes/Document/components/Document.js
  server/models/Document.js
  server/models/Document.test.js
  server/presenters/document.js
  shared/i18n/locales/en_US/translation.json
  shared/theme.js
  shared/utils/getTasks.js
Labels: enhancement

#2338 feat: Auto detect language on login page access
  app/components/Authenticated.js
  app/scenes/Login/Provider.js
  app/scenes/Login/index.js
  app/utils/language.js
  package.json
  shared/i18n/locales/en_US/translation.json
Labels: i18n

#2396 perf: Remove no-longer-used 'backup' columns
  server/models/Document.js
  server/models/Revision.js
Labels: performance

#2372 New Crowdin updates
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#2394 perf: Separate slow joins
  server/models/Document.js
Labels: performance
