Repository outline/outline, pull requests merged in 2022-03, with the labels that each got.

#3171 perf: Navigation of shared trees feels slow
  app/components/Sidebar/Shared.tsx
  app/components/Sidebar/components/SharedDocumentLink.tsx
  app/scenes/Document/Shared.tsx
  app/stores/UiStore.ts
Labels: performance

#3176 New Crowdin updates
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#3233 New Crowdin updates
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ru_RU/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#3257 fix: prevent history from crashing due to missing EditorView
  app/editor/index.tsx
  app/scenes/Document/components/DataLoader.tsx
Labels: more information needed

#3254 chore: `documentStructure` database locking
  server/commands/documentMover.test.ts
  server/commands/documentMover.ts
  server/commands/pinDestroyer.ts
  server/models/Collection.ts
  server/models/Document.test.ts
  server/models/Document.ts
  server/routes/api/documents.ts
Labels: performance

#3293 feat: Small confirmation dialogs
  app/components/Button.tsx
  app/components/Dialogs.tsx
  app/components/Modal.tsx
  app/components/Sidebar/components/TrashLink.tsx
  app/menus/CollectionMenu.tsx
  app/menus/DocumentMenu.tsx
  app/menus/GroupMenu.tsx
  app/stores/DialogsStore.ts
  app/typings/styled-components.d.ts
  shared/i18n/locales/en_US/translation.json
  shared/theme.ts
Labels: lovin-crit
