Repository outline/outline, pull requests merged in 2025-07, with the labels that each got.

#9580 perf: Some small performance improvements in SearchHelper
  server/models/helpers/SearchHelper.ts
Labels: performance

#9564 New Crowdin updates
  shared/i18n/locales/cs_CZ/translation.json
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/en_GB/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/he_IL/translation.json
  shared/i18n/locales/hu_HU/translation.json
  shared/i18n/locales/id_ID/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nb_NO/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ro_RO/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/tr_TR/translation.json
  shared/i18n/locales/uk_UA/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: i18n

#9627 New Crowdin updates
  shared/i18n/locales/cs_CZ/translation.json
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/en_GB/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/he_IL/translation.json
  shared/i18n/locales/hu_HU/translation.json
  shared/i18n/locales/id_ID/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nb_NO/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ro_RO/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/tr_TR/translation.json
  shared/i18n/locales/uk_UA/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#9660 New Crowdin updates
  shared/i18n/locales/cs_CZ/translation.json
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/en_GB/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/he_IL/translation.json
  shared/i18n/locales/hu_HU/translation.json
  shared/i18n/locales/id_ID/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nb_NO/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ro_RO/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/tr_TR/translation.json
  shared/i18n/locales/uk_UA/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#9722 perf: Prefetch references on hover
  app/components/RevisionListItem.tsx
  app/components/Sidebar/components/SidebarLink.tsx
  app/hooks/useClickIntent.ts
  app/scenes/Document/components/ReferenceListItem.tsx
Labels: performance

#9669 New Crowdin updates
  shared/i18n/locales/cs_CZ/translation.json
  shared/i18n/locales/da_DK/translation.json
  shared/i18n/locales/de_DE/translation.json
  shared/i18n/locales/en_GB/translation.json
  shared/i18n/locales/es_ES/translation.json
  shared/i18n/locales/fa_IR/translation.json
  shared/i18n/locales/fr_FR/translation.json
  shared/i18n/locales/he_IL/translation.json
  shared/i18n/locales/hu_HU/translation.json
  shared/i18n/locales/id_ID/translation.json
  shared/i18n/locales/it_IT/translation.json
  shared/i18n/locales/ja_JP/translation.json
  shared/i18n/locales/ko_KR/translation.json
  shared/i18n/locales/nb_NO/translation.json
  shared/i18n/locales/nl_NL/translation.json
  shared/i18n/locales/pl_PL/translation.json
  shared/i18n/locales/pt_BR/translation.json
  shared/i18n/locales/pt_PT/translation.json
  shared/i18n/locales/ro_RO/translation.json
  shared/i18n/locales/sv_SE/translation.json
  shared/i18n/locales/th_TH/translation.json
  shared/i18n/locales/tr_TR/translation.json
  shared/i18n/locales/uk_UA/translation.json
  shared/i18n/locales/vi_VN/translation.json
  shared/i18n/locales/zh_CN/translation.json
  shared/i18n/locales/zh_TW/translation.json
Labels: more information needed

#9733 perf: Restore fast-click functionality
  app/components/Sidebar/components/NavLink.tsx
Labels: performance
